### ISSUE TITLE
Issues - Missing Components

### ISSUE THREAD

**Issue by ljsharp** [sinan-aydogan/tailadmin-laravel#10]
**Describe the bug**

**To Reproduce**
run this command - npm run dev

**Expected behavior**
When running the npm run dev command, errors are raised saying most of the component files are not found as follows:
ENOENT: no such file or directory, open '/resources/js/Jetstream/Input.vue'
ENOENT: no such file or directory, open '/resources/js/Jetstream/Label.vue'
ENOENT: no such file or directory, open '/resources/js/Jetstream/ValidationErrors.vue'

Another issue is that the light and dark theme did not work after it was switched.

**Screenshots**
Screenshot attached
<img width="1680" alt="Screenshot 2024-07-07 at 5 04 47 AM" src="https://github.com/sinan-aydogan/tailadmin-laravel/assets/17466284/4a85c977-fdd0-4288-a7bd-724beb989af2">
<img width="1680" alt="Screenshot 2024-07-07 at 5 04 53 AM" src="https://github.com/sinan-aydogan/tailadmin-laravel/assets/17466284/b2f70e92-cb6e-4c83-9582-7dd410d5f09d">

I would like to thank you for creating this tailwind admin template :)

**Comment by ljsharp** [comment]
I copied the components from the [source code ](https://github.com/sinan-aydogan/tailadmin-laravel/releases/tag/v.1.0.0) The dark and light theme seem to work when the system changes the theme. Thanks

**Comment by ljsharp** [comment]
I've encountered some issues with imports during the npm run build process. Could you please investigate and resolve these bugs to ensure the project builds correctly for production? Thanks
<img width="1680" alt="Screenshot 2024-07-08 at 8 50 10 AM" src="https://github.com/sinan-aydogan/tailadmin-laravel/assets/17466284/88c0187d-9fd3-4bab-9b90-7d0696bfd6d7">

**Comment by sinan-aydogan** [comment]
Building errors resolved with v.2.1.5, thanks for your feedback.
