### ISSUE TITLE
Alert Components

### ISSUE THREAD

**Issue by afsakar** [sinan-aydogan/tailadmin-laravel#10]
When the alerts has more than one line while in mobile, incompatibility occurs in the mobile view.

(Edit: more precisely, alert height remains constant in mobile view.)

![image](https://user-images.githubusercontent.com/75483091/134134685-14016f90-e1e1-4beb-a58b-f307849d7521.jpeg)

**Comment by sinan-aydogan** [comment]
I checked the alert component but i didn't see this problem. Can you share Browser and Resolution with me.

![Screenshot_1](https://user-images.githubusercontent.com/1011324/134199432-f6454138-465b-4527-b224-a718f3b190f1.jpg)

**Comment by afsakar** [comment]
I checked on with safari, chrome and yaani. But still same problem.

**Comment by sinan-aydogan** [comment]
Thanks for your support
