### ISSUE TITLE
Edit Main Menu

### ISSUE THREAD

**Issue by arminkit** [sinan-aydogan/tailadmin-laravel#4]
Hi Dear, thank you, the panel is very useful 
To create a menu, I saw your tutorial, but it didn't work:

[Link Youtube: Menu Management - TailAdmin Components](https://www.youtube.com/watch?v=1pdh4Aga86Y&list=PLbdS49WKsrOXTo_X_Ja6P3zll1yyhoIYN&index=6)

Did I go wrong or is there a new solution?

Thanks

**Comment by sinan-aydogan** [comment]
Can you send menu structure ? Let's check up

**Comment by arminkit** [comment]
I even renamed the mainMenuLinks.js file, but still the default menus were displayed!


>

**Comment by sinan-aydogan** [comment]
You should delete from line 16 to line 326 in mainMenuLinks.js then you can add your links like that sample code is shows. Moreover you should use` npm run hot` to generate dynamic app.js when editing vue files. You have been getting old app.js from the start.

**Comment by arminkit** [comment]
Yes, it was my mistake
I had completely forgotten about this
Thank you for your quick reply
thank you
